### ISSUE TITLE
Localisations should be type safe

### ISSUE THREAD

**Issue by andreievg** [openmsupply/open-msupply#1266]
Based on this discussion: https://github.com/openmsupply/open-msupply/pull/1252#discussion_r1120823118, please read it for context.

Main concern is that localisations are not fully type safe:

**A - use multiple namespaces** 
Works
```diff
+const CheckLocalisations = () => {
+  const t = useTranslation('replenishment');
+  return <div>{t('error.amc-is-zero')}</div>;
+};
+
 const Host = () => (
   <React.Suspense fallback={<div />}>
     <IntlProvider>
+      <CheckLocalisations />
```
Not type error, but logic error
```diff
+const CheckLocalisations = () => {
+  const t = useTranslation(['inventory', 'replenishment']);
+  return <div>{t('error.amc-is-zero')}</div>;
+};
+
 const Host = () => (
   <React.Suspense fallback={<div />}>
     <IntlProvider>
+      <CheckLocalisations />
```
**B - string doesn't match namespace**
No type error but logic error
```diff
+const CheckLocalisations = () => {
+  const t = useTranslation('inventory');
+  return <div>{t('error.amc-is-zero')}</div>;
+};
+
 const Host = () => (
   <React.Suspense fallback={<div />}>
     <IntlProvider>
+      <CheckLocalisations />
```

There are a couple of options to fix the issue:
 1. Upgrade i18next, would assume they've fixed the type safety and multiple namespace issues, to be confirmed
 2. Use one file for translations

`2` also reduces chance of duplicates as per screenshot below, if we have duplicates it's hard to figure out which duplicate instance is used where (can't just do a search, need to also know what namespace is imported in that file). 

In https://github.com/openmsupply/open-msupply/pull/1252#discussion_r1123631277 @mark-prins lists some valid benefits of splitting translations to their own files, most practical ones seems to be: reduction of conflicts (especially considering weblate, the UI for translations), one file would eventually be unwieldy. 

If grouping into files is done by `type` rather then `context` (i.e. all errors in one file) I think it would reduce chance of duplicates and would actually make localisation files easier to manage/find.

### Tasks

- [ ] Fix existing use cases of `A` (see screenshot below)
- [ ] Upgrade 18next and check logic errors above
- [ ] Agree on translation file structures
- [ ] Automate reduction of translation conflicts (i.e. an action to re-commit translation files after running linter/sorting, for every PR) ?

### Screenshots

**duplicates**

![Screenshot 2023-03-03 at 10 42 37 AM](https://user-images.githubusercontent.com/26194949/222569033-8911f307-645f-4a20-9964-80df06c6f465.png)

**existing use cases of A**

![Screenshot 2023-03-01 at 5 30 40 PM](https://user-images.githubusercontent.com/26194949/222568810-2936644e-7786-47d5-bc91-da019f485628.png)

**Comment by mark-prins** [comment]
Nice! thanks - would be good to get these changes in place, and to agree on a structure for the translation files

> If grouping into files is done by type rather then context (i.e. all errors in one file) I think it would reduce chance of duplicates and would actually make localisation files easier to manage/find.

I like this idea! Given the understanding that we don't benefit from download size due to caching and cross-cutting site usage, splitting the files by type is probably easiest for devs

**Comment by andreievg** [comment]
Something else just noticed, the replenishment.json and distribution.json has a few duplicates, maybe should be consolidated in common.json

**Comment by andreievg** [comment]
I think with one common.json this is now a lot more type safe
