### ISSUE TITLE
Program Requisitions

### ISSUE THREAD

**Issue by andreievg** [openmsupply/open-msupply#1451]
## Program Requisitions

Base requirement is replicating [mSupply program functionality](https://docs.msupply.org.nz/items:programs), minus regimen/indicator data.

### Primary

- [x] https://github.com/openmsupply/open-msupply/issues/1489 (name_tags)
- [x] https://github.com/openmsupply/open-msupply/issues/1480
- [x] https://github.com/openmsupply/open-msupply/issues/1481
- [x] https://github.com/openmsupply/open-msupply/issues/1504
- [x] https://github.com/openmsupply/open-msupply/issues/1506
- [x] https://github.com/openmsupply/open-msupply/issues/1508
- [x] https://github.com/openmsupply/open-msupply/issues/1509
- [x] https://github.com/openmsupply/open-msupply/issues/1510
- [x] https://github.com/openmsupply/open-msupply/issues/1507
- [x] https://github.com/openmsupply/open-msupply/issues/1648
- [x] https://github.com/openmsupply/open-msupply/issues/1656
- [x] https://github.com/openmsupply/open-msupply/issues/1657
- [x] https://github.com/openmsupply/open-msupply/issues/1655
- [x] https://github.com/openmsupply/open-msupply/issues/1653

### Secondary 
- [ ] https://github.com/openmsupply/open-msupply/issues/1486
- [ ] Tidy up styles in program requisition options component and in the create requisition modal
    * https://github.com/openmsupply/open-msupply/pull/1531#pullrequestreview-1384589315
- [ ] There is a TODO in program_supplier repository related to diesel deserialisation error, need to make sure this is addressed (would probably mean creating an issue in diesel-rs, with replication)

## Scope

**Need to confirm this is what we need for Second level desktop warehouse milestone**

* Restrict program order by items
* Restrict program order by periods
* Pre-fill max MOS and threshold MOS in the order

1. Confirm above requirements ? 

In mSupply we have fine grained configurations for a program facility that apply by `store tag`, stores with that tag will have this program `linked` and available/usable. Configurations are quite extensible, since we won't have time to re-write how this configurations are created/updated we have to translate them to a more preferred structure and for next milestone need to understand the minimum configurations.

2. Would these be sufficient for configurations ?

* Program instance/group is configured by store tag
 
For each  `Program instance/group` we can configure:
* Period schedule (i.e. monthly, bi-monthly odd, bi-monthly even etc..)
* Can have a number of order types (I think in real life scenarior there is only two types, normal and emergency ?)

For each `order type` we can configure:
* How many orders of this type can be made in a period
* Name of the order
* Max MOS
* Threshold MOS
* ~~Is it emergency order~~ Is this needed ? We can deduce by name or have a more strict schema that only allows normal and emergency order
* ~~Maximum number of lines in that order~~ (this was used for emergency order mainly)

3. Are we only dealing with internal orders or requisitions (and do we need to add manual requisitions) ? 

## Design

Need to consider:
* Display program and order type in lists (internal order/requisition)
* Restrict order by items
* Restrict order by periods
* Pre-fill max MOS and threshold MOS form program configurations, are those editable ?

4. Do we need to think about displaying any program information in invoices ?
5. Once internal order is created, can we edit it's type period etc.. ?
6. Do we need to enforce reasons when request quantity differs from suggested ?
7. Can we only order from a name with matching program ?

## Schema

in mSupply, we have the following in master list `programSettings` field:
```json
{
    "storeTags": {
        "firstLevelHIV": {
            "periodScheduleName": "Monthly",
            "orderTypes": [
                {
                    "name": "Normal",
                    "type": "Order type",
                    "isEmergency": false,
                    "maxMOS": 3,
                    "thresholdMOS": 1,
                    "maxOrdersPerPeriod": 1,
                    "maxEmergencyOrders": ""
                },
                {
                    "name": "Emergency",
                    "type": "Order type",
                    "isEmergency": true,
                    "maxMOS": 3,
                    "thresholdMOS": 1,
                    "maxOrdersPerPeriod": 1,
                    "maxEmergencyOrders": 5
                }
            ]
        }
    }
}
```
Above `maxEmergencyOrders` = how many lines per order

This can be turned into schema (during sync)

```mermaid
erDiagram
    name_tag }o--o{ name_tag_join : name_tag_id
    name_tag {
        string id
        string name
    }
    name_tag_join {
        string id
        string name_id
        string name_tag_id
    }
    store }o--o{ name_tag_join : name_id
    store {
        string id
        string name
        string name_id
    }
 
    program ||--|| master_list: master_list_id
    master_list {
        string id
        stirng name
    }
    program {
        string name
        string master_list_id
    }
    program_settings ||--|| period_schedule: period_schedule_id
    program_settings ||--|| program: program_id
    program_settings ||--|| name_tag: name_tag_id
    program_settings {
        string id
        string name_tag_id
        string program_id
        string period_schedule_id
    }
    program_order_type }|--|| program_settings : program_settings_id
    program_order_type {
        string id
        string prorgam_settings_id
        string name
        number threadsholdMOS
        number maxMOS
        number maxOrderPerPeriod
    }
    period_schedule {
        string id
        string name
    }
    period }|--|| period_schedule : period_schedule_id
    period {
        string id
        string period_schedule_id
        string name
        date to
        date from
    }
```

## API

If we go with mirroring mSupply functionality, front end would need to extend new order modal (currently only shows Suppliers), in [mSupply](https://docs.msupply.org.nz/items:programs) and [Mobile](https://docs.msupply.foundation/mobile/order_and_receive/supplier-requisitions-program/) we have: 

![mSupply internal order](https://docs.msupply.org.nz/_media/items:program_new_internal_order.png?w=400&tok=59f8ad)

![mobile supplier requisition](https://docs.msupply.foundation/mobile/introduction/images/supplier_program_order.png)

For that screen we would need to know:

**To display program options**

```graphql
programSettings {
   programs: ProgramSetting[]
}

ProgramSetting {
   # program name, i.e. HIV, TB
   name: String 
   orderTypes: OrderType[]
}

OrderType {
    # i.e. Normal/Emergency
    name: String
    id: String
    maxMOS: Number
    thresholdMOS: Number
    isEmergency: boolean
    availablePeriods: Period[]
}

Period {
   id: String
    name: String
    from: Date,
    to: Date
}
```

**To create program requisition**

Would need a new type of insertRequisition `insertProgramRequestRequisition`

```graphql
insertProgramRequestRequisitionInput {
   otherPartyId: String
   orderTypeId: String
   periodId: String
}
```

Just noticed there are 3 API requests when requisition is created, should just be one (result of create should have serial number etc..)

## Other notes

In program requisition we should lock some UI elements for editing (with f/e and b/e), and would need to add some extra program information to the record, since we don't have soft delete, we would copy data from orderType/programSettings to program requisition

**Comment by andreievg** [comment]
UI changes:

* Requisition List (response and request), add these columns (if program requisitions are configured)
   * Program name
   * Order type
   * Period name
* When creating request requisition if program requisitions are enabled have an option between general and program requisition, for program requisition option:
    * Select program
    * Select suppliers, only the ones with the program
    * Select order type
    * Select period
* When displaying request requisition should
   * Show program
   * Show order type
   * Show period
   * Disable changes to supplier, maxMOS, thresholdMOS, period, order type, program, item addition/deletion
 * When displaying response requisition should
   * Show program
   * Show order type
   * Show period
   * Disable addition/deletion of items

**Comment by andreievg** [comment]
Looks like we have name_tag (syncs as central data) and name_tag_join (syncs as remote data) table in mSupply, these tables mirror store tags already.  We should use those instead of store tags.

kudos @jmbrunskill and @Chris-Petty for identifying this.

**Comment by andreievg** [comment]
I think we should be a little bit more specific and differentiate between patient and requisition programs:
programSettings -> programRequisitionSettings
programOrderType -> programRequisitionOrderType

the core `program` table should still be names `program`

**Comment by andreievg** [comment]
> - [ ] https://github.com/openmsupply/open-msupply/issues/1486

This should technically be ok, if we find it problematic can always re-set, just have to be mindful if existing sites that were initialised prior to program requisition changes (possibly first mobile deployment sites), need to use program functionality, we would need to add a migration that resets integration status of sync_buffer rows for master list

> - [ ] Tidy up styles in program requisition options component and in the create requisition modal
    * https://github.com/openmsupply/open-msupply/pull/1531#pullrequestreview-1384589315

I think styles must be ok since we didn't hear any negative comments from PM/users

> - [ ] There is a TODO in program_supplier repository related to diesel deserialisation error, need to make sure this is addressed (would probably mean creating an issue in diesel-rs, with replication)

This is not really causing any issues, and might be improved with diesel upgrade ¯\_(ツ)_/¯ 

Closing, I think this epic is complete, thanks everyone
