### ISSUE TITLE
Sync v5 

### ISSUE THREAD

**Issue by Chris-Petty** [openmsupply/open-msupply#156]
</br>
</br>

**note:** Carry over tasks from this epic were moved to https://github.com/openmsupply/open-msupply/issues/608
</br>
</br>

- [x] Send correct headers `app-name` and `app-version` (possibly already done, needs to work for v3 push for short term as well)
- [x] Create `sync-v5` feature branch
- [x] #165 
- [x] Sync V5 handle awaiting integration
- [x] #246
- [x] #244
- [x] https://github.com/openmsupply/open-msupply/issues/177
- [x] #254
- [x] #229
- [x] Tests to have info
- [x] #257
- [x] #249
- [x] #148 
- [x] #197
- [ ] Is it possible to change visibility via name store join without deleting it ?
- [ ] Do we need to only integrate remote data deletes if site is not current site ?
- [x] #250
- [x] #357
- [x] #327
- [x] #330
- [x] #333
- [x] #338

## Transfers

- [x] Handle generating inbound shipments after pulling from `queued_records`
- [x] Handle generating response requisitions after pulling from `queued_records` 
- [x] In open-msupply, only immediately generate transfers if both stores are active on the remote

For the above, we basically want the sync processor to use change_log (crawl though it and do the actions it needs), and we just trigger sync processor when we need to (after sync, after insert/update/delete of request requisition and outbound shipment). Using change_log would mean it needs to be more consumable (should not just return id and record type, but the records themselves). Also we shouldn't try to push records that don't belong to current site.
Sync processor log ?

**Comment by andreievg** [comment]
To do to the list:
- [ ] V5 push
- [ ] V5 await integration

Currently, omSupply is working with V3 push and V5 pull (remote, central). A few things are missing though (like inter sync site transfers), but this is not required for immediate customers (the ones in pipeline for June). To keep things 'stable', we aim to:
1. Create sync/v5 branch for omSupply  (since omSupply main is tested, existing v3 pull and v5 push works, so let's not break it with v5 push PRs).
2. Sync/v5 branch in mSupply to be updated from master (not develop), so that it can be built at any time and be a 'stable' branch for omSupply demo/deploy.

If there are any breaking changes to v3 push or v5 pull, we would need to put those through straight away to omSupply and redeploy (so hopefully this is avoided). And in sync/v5 omSupply branch we can work on v5 push and other associated bits and pieces.

Quite a bit of testing is needed to get sync/v5 mSupply branch merged into mainstream (v5 push required some minor changes to v1, and thus needs to be thoroughly tested), but we would only need sync/v5 branch merged if we want existing mSupply sites to use omSupply (which implies backwards compatibility), it doesn't look like we have immediate customers wanting to do this, so technically speaking, merge of sync/v5 is not urgent as long as it doesn't lag behind main. (and we can use it as a fork/trunk mSupply build for omSupply)

**Comment by andreievg** [comment]
- [ ] Use cursor instead of record acknowledgement (also would mean we can use one combined type for central and remote sync record)

**Comment by andreievg** [comment]
- [ ] Dynamic batch size, https://github.com/openmsupply/open-msupply/pull/328/files/351494eeb99c88e1d253d03f1c254961381ba585#r922920627

**Comment by andreievg** [comment]
Had a discussion with Chris:

* After transfer work, will close this issue and leftovers will go into `sync cary over/improvements` issue
* Edge case that we should deal with, is item not in master list but have stock for it, a few ways to achieve this scenario (master list adjustment, inbound shipment transfer received with items not in master list for store, etc..)
* Use cursor when pulling remote records (requires cursor being added to remote queue pull)
* Integration test for transfers should be 2 sites, but extend to be 3 site in the future

**Comment by andreievg** [comment]
## Transfers

- [ ] Rename sync processor (or extend to have transfer processor). Sync processor would be a combination of operations (transfers, messages, merge) to use Sync Processor with visitor patter of all possible operations would be quite overwhelming and quite a lot of logic to dig through, it's better if sync processor is split into different operations (might even be requisition_transfer_processor and invoice_transfer_processor, as existing logic for preparing record for visitors of all transfers has quite a bit of repeating conditions).
- [ ] Add name_id and store_id to change_log (for requisitions, invoices and requisition_lines, invoice_lines). I think the simplest way to achieve this is with select inside triggers (should also work for deletes). 
- [ ] Add filter for name_id, store_id and table name to change_log
- [ ] Sync/Transfer processor to use change log (also simplify processors slightly)
- [ ] After initialisation and sync use change log for sync processor (filtered as per below diagram)
- [ ] After insert/update/delete of invoice/requisition use change log for sync processor (filtered as per below diagram)
- [ ] Use filtered change log in push (as per below diagram)
- [ ] Integration test for transfers (two sites with as many combination as possible, like sending transfers before/after initialisation, deleting records)

## Other
- [ ] Remove site id from sync settings input/mutations, and relocate query to get site id before going out of bootstrap mode
- [ ] Update from develop

## More edge cases
- [ ] If there are deletes of transfers that don't belong to current site in sync queue, and initialisation is requested, they are removed, could lead to InboundShipment of picked status not being deleted
- [ ] Similar, merge records might be removed when initialisation is requested

[Below diagram in google drive](https://app.diagrams.net/#G1o_xRQAhjVsnqhxhJEu9dY6AZ_lJfG9co)
![omSupply Transfer Processor drawio](https://user-images.githubusercontent.com/26194949/185845794-27198d2d-f3c1-497e-900b-40c3b7721f8e.png)

**Comment by andreievg** [comment]
Added a comment about cary over tasks being move at the root comment in this issue, closing as it's getting a bit messy
