### ISSUE TITLE
v1.1.14 Documentation

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/open-msupply#1866]
## Is your feature request related to a problem? Please describe 👀
Update the documentation to reflect user-facing changes in v1.1.14

- [x] #1695 Barcode scanning: add keyboard shortcut
- [x] #1725 Barcode scanning: Could update the docs about updating a stock line and mention that barcodes sync
- [x] #1726 Inbound shipment: info message change
- [x] #1771 Internal order: add column for authorised quantity in packs
- [x] #1736 Internal order: enter quantity in packs
- [x] #1735 Local authorisation
- [x] #1646 Internal order: add unit column
- [x] #1788 Outbound shipment: placeholder row has total removed
- [x] #1758 Stocktake: filter list by item code / name
- [x] #1703 & #1808 Stocktake: add unit to table and modal
- [x] #1697 Internal order: Cannot use a program master list when adding items by master list
- [x] Add a link to the [releases](https://github.com/openmsupply/open-msupply/releases) page explaining where to download and which file is for what. Tie in with [what platforms are supported](https://docs.msupply.foundation/docs/introduction/introduction/#what-platforms-are-supported)

### Moneyworks Jobcode 🧰

DJUNCUST

**Comment by mark-prins** [comment]
Links to the new and updated documentation:

- Barcode scanning: [add keyboard shortcut](https://docs.msupply.foundation/docs/distribution/outbound_shipments/barcode-scanning)
- Barcode scanning: [Updating a stock line and mention that barcodes sync](https://docs.msupply.foundation/)
- Internal order: [add column for authorised quantity in packs](https://docs.msupply.foundation/)
- Internal order: [enter quantity in packs](https://docs.msupply.foundation/)
- [Local authorisation](https://docs.msupply.foundation/docs/replenishment/internal-orders/#local-approval-process)
- Internal order: [add unit column](https://docs.msupply.foundation/)
- Outbound shipment: [info message change](https://docs.msupply.foundation/)
- Outbound shipment: [placeholder row has total removed](https://docs.msupply.foundation/)
- Stocktake: [filter list by item code / name](https://docs.msupply.foundation/)
- Stocktake: [add unit to table and modal](https://docs.msupply.foundation/)
- Internal order: [Cannot use a program master list when adding items by master list](https://docs.msupply.foundation/)
- [Add a link to the releases](https://docs.msupply.foundation/)
