### ISSUE TITLE
Initial MVP implementation of a prescription window

### ISSUE THREAD

**Issue by DhanyaHerath** [openmsupply/open-msupply#1939]
Current programs module already allow for patient creation, so could use that for creating patients in dispensary. 

Patient search on central is also being worked on.

### Programs Overlap
- [x] #1947 
- [x] Currently cannot view patients who aren't created with a patient document  #1094

### Table/Sync changes
- [x] #1948

#### Inserts
- [x] #1949
- [x] #1950 

#### Updates
- [x] #1951
- [x] #1952 

#### Deletes
- [x] #1953 

#### Batch
- [x] #1976 

#### UI
- [x] #1954
- [x] #1956
- [x] #1960 
### Discussion 
- [ ] Unallocated lines and Add Master List button

### Future work
- [ ] #502
- [ ] Auto allocate stock straight away for faster input for pharmacists
- [ ] Delete/Alert user if navigating away without any prescription lines
- [ ] Invoice status should change to `Picked` if an invoice line has been added (i.e. invoice not empty)
- [ ] Being able to `add` or `edit` patients in the prescription window
- [ ] Patient history
- [ ] Label printing
- [ ] Remote patient search
- [ ] Currency handling or receipts
- [ ] Patient notes
- [ ] Auto allocate when quantity is chosen
- [ ] Backorders

## Is your feature request related to a problem? Please describe 👀
This issue will need some design and constraints placed around it, but the key thing we want to do is create a very MVP version of the prescription window. This should begin as a copy of the existing outbound shipment window, but allow for searching for patients. We want to make it quite minimal in terms of how much design we put in because this is a highly used window in mSupply, and it should have a proper requirements-gathering phase for the full implementation. 

## Describe the solution you'd like 🎁
An MVP version of a prescription window, with the following things included (nb. most things here can be discussed, except for the excluded ones, which I suggest we keep excluded): 

Menu bar: 
- You should be able to create a new prescription 
- You should be able to see a list of prescriptions, separate to outbound shipments
- I would suggest having this as a new menu option under Distribution for now 
- There should be a way to turn on dispensary mode without turning on the Patient Programs module. 

Prescription window: 
- The invoice should have a status of `new`, `allocated` and `finalised` (this could be up for discussion) 
         - When you click OK after first creating a prescription, it should go to the allocated stage. We should make it basically impossible to have a prescription where the items are not taken out of stock (if the lines exist)
- The invoice should allow you to search for patients in the search box where you currently search for Customer names 
- The invoice should allow you to add items as it currently does. Allowing adding from masterlist can also remain, if it is easy to keep, but it's not a must-have. 
-  The invoice should have a new search to allow searching for clinicians 

Adding a line:
- When you add a line, you should be able to add a note.
- It would be helpful if the first line of available stock (should be the first to expire) was automatically selected. 

Next up, good to haves: 
-  When you add a line and create a note for that line, it would be helpful if the note could take into account abbreviations from the `abbreviations` table on mSupply, and expand that out. This can be in a second phase though. 
- Being able to add and see a list of patients 

Exclusions: 
- In this implementation, we will not allow creating repeats 
- We will not show patient history 
- We will not have label printing  
- We will not have remote patient search 
- We will not have currency handling or receipts
- We will exclude patient notes
- In mSupply, it will automatically select the first available stockline when you choose a quantity. We won't do that here (yet) 
- We will exclude being able to add and edit patients directly from the prescription window
- We will exclude backorders: users must allocate stock before they can change status to picked

### Additional context 💌

The current mSupply implementation is described [here](https://docs.msupply.org.nz/dispensing:prescription_entry) 

### Moneyworks Jobcode 🧰
OMS:MVP | Open mSupply MVP Prescription Module
-- | --

**Comment by DhanyaHerath** [comment]
Description updated after discussion!

**Comment by roxy-dao** [comment]
Issue placeholder

**Comment by DhanyaHerath** [comment]
Thanks @roxy-dao! I would say the [fuzzy patient search](https://github.com/openmsupply/open-msupply/issues/502) isn't part of an MVP version. Could we move this issue list into the issue description itself please? Makes it easier to reference, and means that we can use Github's tracking :)

**Comment by andreievg** [comment]
I think to future work we should add, being able to `add` and `edit` patients on the go (from prescription window)

**Comment by DhanyaHerath** [comment]
Added, thanks @andreievg

**Comment by mark-prins** [comment]
Moving the next phase of work into #2071
