### ISSUE TITLE
Customised filter list

### ISSUE THREAD

**Issue by roxy-dao** [openmsupply/open-msupply#2282]
## Is your feature request related to a problem? Please describe 👀
Coldchain will be implementing a wide range of filters for each page.

## Describe the solution you'd like 🎁
Implement a filter like in `Conforma` (find internal docs [here](https://github.com/openmsupply/conforma-web-app/blob/develop/docs/internal/Filters-for-Applications.md) and example general filter [here](https://github.com/openmsupply/conforma-web-app/blob/develop/src/containers/TemplateBuilder/template/General/Filters.tsx)) where the user can select which filters they would like to filter by. Currently, there will be no default filters to show in the header. They will all appear as they are selected through the filter dropdown. Will also need a way to be able to clear the filters as needed. See screenshots below for UI mockup.

Will also need to implement two filter options that are currently not available in om: `Datetime range filter`

<img width="796" alt="Screenshot 2023-09-26 at 9 27 21 AM" src="https://github.com/openmsupply/open-msupply/assets/61820074/fc676d0f-2ce0-4a81-9a2a-5693e5bcdeea">
<img width="782" alt="Screenshot 2023-09-26 at 9 27 30 AM" src="https://github.com/openmsupply/open-msupply/assets/61820074/dd4270f0-bcbc-4f56-b65c-3ab20080322a">

### Estimate
5 days

### Moneyworks Jobcode 🧰
OMS:COLC

### Issues:

- [x] Initial filter base mechanism #2350
- [x] Agree on UI/UX
- [x] Text filter  #2350
- [x] Enum filter  #2350
- [x] Date filter #2351
- [x] Time filter #2351
- [x] Number filter #2352 
- [ ] Implement for Cold chain #2353
- [ ] Small tweaks/improvements #2382

**Comment by roxy-dao** [comment]
Related to #2274

**Comment by CarlosNZ** [comment]
So, the generic filter types will be:

- text
- enum (enum options will be passed in as props)
- date range
- date/time range (might be just a variant of "date range")
- number range

**Comment by mark-prins** [comment]
This issue is already too large for a single issue, in my opinion.
Can you remove the `Implement in other places (where appropriate)` task - that can be raised as a separate issue when the time comes.

**Comment by CarlosNZ** [comment]
> This issue is already too large for a single issue, in my opinion.

Happy to break them out into further issues, was just making sure we had the overall scope correct.

> Can you remove the `Implement in other places (where appropriate)` task - that can be raised as a separate issue when the time comes.

👍

**Comment by CarlosNZ** [comment]
Added issues, with links added to original issue post

**Comment by roxy-dao** [comment]
Closing since issues mostly implemented, just the extra stuff left but that has its own issue

**Comment by nisha-dangol** [comment]
Testing as part of [v1.6 Release-test](https://docs.google.com/spreadsheets/d/1MGW4v2BoaYLToUKTTglBrsrkBBQl-d079rtEeDhqXsk/edit#gid=915349711)
- [ ] #2350
- [x] #2351
- [ ] #2352 
- [ ] #2353
- [ ] #2382
