### ISSUE TITLE
Deployment ready

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/open-msupply#427]
Coming from https://github.com/openmsupply/remote-server/issues/1016
and https://github.com/openmsupply/remote-server/issues/788
and https://github.com/openmsupply/remote-server/issues/560

## Requirements

- [x] Can download an installer and run app locally, with clients available on local network #22
- [x] Can set up a cloud server running the app #22
- [x] Can install android app
- [x] Create and configure a windows service as part of the installer  #22
- [x] Investigate the current solution to the issue of running postgres on windows
- [x] demo server installer #627 new datafile for that? Ideally yes, not right now..
- [x] download site?
- ~[ ] version check on mSupply?~
- [x] Remove the default reports #624 

and then ( possibly not for initial release )

- [x] Can upgrade the above with upgrader
- ~[ ] Database migrations ( yes, I know. I keep saying this. )~

**Comment by mark-prins** [comment]
Client issue which needs some robustness before v1: 
with a server restart, the oms service requires 4D to be running, with the HTTP server accepting requests before starting.
Even with the oms service depending on 4D ( see below ) the timing can cause oms to fail to start correctly, entering bootstrap mode:

![Screen Shot 2022-08-02 at 11 24 46 AM](https://user-images.githubusercontent.com/9192912/182262038-3fd40ae7-17a5-4e63-a853-66498d91efe3.png)

Current configuration is to have 4D running automatically, with oms running automatic (delayed start) and with the dependency.

**Comment by mark-prins** [comment]
Closing this one - I think everything is in place now
