### ISSUE TITLE
Electron client improvements (2 of 2)

### ISSUE THREAD

**Issue by andreievg** [openmsupply/open-msupply#58]
- [x] More security https://github.com/openmsupply/open-msupply/pull/40#discussion_r882213131
- [ ] Reduce cpu usage (could be because it's trying to get local ip all the time) `discovery.on('response'` definitely captures all of the responses, not just the ones sent in a query https://github.com/openmsupply/open-msupply/pull/40#issuecomment-1138055337
- [x] Properly stop and start discovery (remove listeners), and maybe use state https://github.com/openmsupply/open-msupply/pull/40#discussion_r882229928
- [x] https://github.com/openmsupply/open-msupply/issues/79  Improve frontEndHostDisplay https://github.com/openmsupply/open-msupply/pull/40#discussion_r882291311
- [x] https://github.com/openmsupply/open-msupply/issues/79 How should the server discovery ui look ? https://github.com/openmsupply/open-msupply/pull/40#discussion_r882292899
- [x] https://github.com/openmsupply/open-msupply/issues/79 Should we keep last connected server in local storage and connect to it if discovered ? https://github.com/openmsupply/open-msupply/pull/40#discussion_r882303808
- [ ] How should windows behave in mac ? https://github.com/openmsupply/open-msupply/pull/40#discussion_r880378566
- [x] For dev on served front end interacting with client, we might want electron client to use webpack dev bundled of front end vs going through the server https://github.com/openmsupply/open-msupply/pull/40#discussion_r880377247
- [ ] Explore other libraries for discovery (with more control over the listener thread): https://github.com/openmsupply/open-msupply/pull/40#discussion_r882225031
- [x] Generate self signed cert on server startup in production if one doesn't already exist
- [x] https://github.com/openmsupply/open-msupply/issues/79 Make sure. translations can be shown (or remove use of them): https://github.com/openmsupply/open-msupply/pull/77#discussion_r886222422

**Comment by mark-prins** [comment]
Moved #1,3,8 & 10 to #492 to get that in for v1 release.

**Comment by mark-prins** [comment]
we've discussed the windows on mac (summary: all good as it is) and have implemented a different discovery, so closing this issue. Please open a new one if you disagree.
