### ISSUE TITLE
Sync cary over 14-09

### ISSUE THREAD

**Issue by andreievg** [openmsupply/open-msupply#608]
# Sync Cary Over 14/09

Carry over from https://github.com/openmsupply/open-msupply/issues/156

## Sync v5 branch

- [ ] Update form dev and merge
- [ ] Make sure all TODO in diff in this [PR are summaries](https://github.com/openmsupply/open-msupply/pull/587) before merge

## Questions

* Is it possible to change visibility of name to store in mSupply withouth deleting it ?
* How does pricing work in transfers ?

## Safety

- [ ] Remote data deletes are only allowed for `foreign` records
- [ ] Owned data integrated only during initialisation ?
- [ ] Extra protection in transfer processors for possible circular updates (inifinte looping), some [comments here](https://github.com/openmsupply/open-msupply/pull/579#discussion_r969158425)

## Manual Tests

- [ ] Write up manual cases

## Edge Cases

- [ ] When name_id is changed for shipment, and it's already synced and other half created (outbound shipment in picked status and inbound shipment created), this would cause original inbound shipment to be orphaned in picked status. For name_id changes after picked status should delete and re-created outbound shipment (in service). So another mutation to change name_id (https://github.com/openmsupply/open-msupply/issues/188)
- [ ] It's possible to have stock for an item that is not in master list (shoudl be able to still issue and do stocktake for these items)
- [ ] If there are deletes for transfers in sync queue for foreign site on central server, and that foreign site is `re-initialised`, sync queue will be cleared and we loose the record of those deletes (is the same true for merge records ?)

## Improvements

- [ ] Use cursors for remote sync instead of acknowledgement (this is already implemented in mSupply), and align central and remote data shape in mSupply (also use cursor instead of id)
- [ ] Batch size to be adjustable (setting via mutation). We have more advanced batch size handling in mSupply Mobile, I am not sure if complexity justifies it (vs just increasing batch size)
- [ ] Transfer itegration tests across more then 2 sites ?
- [ ] Quite often we need to know if store and name is active on site, which requires database query, ideally this should be available in memory store (ideally). Transfers check this and invoice_line translator checks this.
- [ ] Should system user be used/displayed for transfer creation/edit ?
- [ ] It would be good if constraints are always enforced (for linked requisitions and linked invoices, extra `circular` translator that adds these, vs removing referencial constraints, does this work for deletes ?)

## Loggin/Errors

Need to have a discussion of logging and error handling some questions to answer
* What should be considered `unrecoverable` server state that requires stopping server
* What problems/errors are non critical and can be logged
* How do we log those errors
* How do we inform our team about these error (and how much to log to allow bug replication)

## Other areas

- [ ] Remove indexes for invoice status and use `match` statements as [per this](https://github.com/openmsupply/open-msupply/compare/10f7c18a4905b4c0b8ce2cfb8a2d9aad59f6b28b...93a3ad24f6fede8a0555b413b15ec481774cc9e7)
- [ ] Another test initialisation method was created, it creates service provider and service context and processor handle, we should use just one helper to create test state/ctx (the one with all of the provisions). Also changed to use struct as test context result and destructure with optionals, to avoid propogating changes to tests when new field is added to this struct

## Documentation

- [ ] Full sync docs

**Comment by richardmoizeau** [comment]
> * Should we copy over comment and their reference from requisition, or display those separately ? What are those field meant to be representing (what is the difference between their reference and comment ? Since we are guaranteed to have the other half of the transfer on site we can easily look those up, and doesn't it feel wrong to have comment and their reference that was transferred from request to response requisition to be editable ? [578 requisition transfer processor #579 (comment)](https://github.com/openmsupply/open-msupply/pull/579#discussion_r970263494), [578 requisition transfer processor #579 (comment)](https://github.com/openmsupply/open-msupply/pull/579#discussion_r970168168)



Reference: a reference (ok genius) that can be easily looked up. If dealing with external stakeholders, usually a way to retrieve a document without knowing the "mSupply" transaction number. Example: HIV-2022/12

Comments: it's more a message or a communication that could be meant for internal or external stakeholders (from a customer to a supplier: "please do not send me expired products", example of internal comms: "please put away the received goods in the fridge immediately"

I also think that the link to related documents should not appear in comments or reference. If we have to do it, then I think comments is more appropriate. But related doc should be available as a separate data I think. 

Sorry if I'm bringing additional confusion or if I'm preaching to the choir ;)

**Comment by andreievg** [comment]
I had a quick look in the context of Android Sabilisation milestone, can only see one thing that can/should be prioritised :

* It's possible to have stock for an item that is not in master list (should be able to still issue and do stocktake for these items)

Will discuss with team and see if this needs to be prioritised

**Comment by andreievg** [comment]
Chris Petty, [23/03/2023 at 9:50:13 AM]:
...A common story in the wild is to take a regular facility name (a pharmacy not on mSupply yet), create a store for it and sync it to a new mobile device. Imminently these devices will be often installed with omSupply! 🎉

Part of the sync initialisation code will send all the past customer invoices relating to the name to the omsupply site. As it is, this could include years of customer invoices... I don't think I've brought this up before, so my question is; do we do anything to not generate inbound shipments from customer invoices that are ancient?

mSupply had a similar issue a couple years ago, but potentially not as bad. The solution there was that if a store/site user opened supplier invoice sent from another store, it'd check the creation time of that invoice against the logged time of when the store was created.

The store table does have a created_date -  omSupply could use this to put a halt on looking too far back when creating transfers (if it doesn't already!).

Mark Glover, [23/03/2023 at 9:58:06 AM (23/03/2023 at 9:58:39 AM)]:
I might be misunderstanding what you have said, but I'm pretty sure that behaviour used to be that historic supplying store CIs do NOT get synced to the new store as SIs (PNG did 300 sites last year and they did not get any old SIs.)  We certainly don't want ancient SIs appearing in the customer store.  AFAIK, only sending store CIs created AFTER creation of the receiving store get 'sent' (regardless of sync).

I would LOVE the store table getting a created_date  This would be very helpful in reporting deployment progress.

**Comment by andreievg** [comment]
> Chris Petty, [23/03/2023 at 9:50:13 AM]: ...A common story in the wild is to take a regular facility name (a pharmacy not on mSupply yet), create a store for it and sync it to a new mobile device. Imminently these devices will be often installed with omSupply! 🎉
> 
> Part of the sync initialisation code will send all the past customer invoices relating to the name to the omsupply site. As it is, this could include years of customer invoices... I don't think I've brought this up before, so my question is; do we do anything to not generate inbound shipments from customer invoices that are ancient?
> 
> mSupply had a similar issue a couple years ago, but potentially not as bad. The solution there was that if a store/site user opened supplier invoice sent from another store, it'd check the creation time of that invoice against the logged time of when the store was created.
> 
> The store table does have a created_date - omSupply could use this to put a halt on looking too far back when creating transfers (if it doesn't already!).
> 
> Mark Glover, [23/03/2023 at 9:58:06 AM (23/03/2023 at 9:58:39 AM)]: I might be misunderstanding what you have said, but I'm pretty sure that behaviour used to be that historic supplying store CIs do NOT get synced to the new store as SIs (PNG did 300 sites last year and they did not get any old SIs.) We certainly don't want ancient SIs appearing in the customer store. AFAIK, only sending store CIs created AFTER creation of the receiving store get 'sent' (regardless of sync).
> 
> I would LOVE the store table getting a created_date This would be very helpful in reporting deployment progress.

This was partially dealt with, and will be deal with further here: https://github.com/msupply-foundation/open-msupply/issues/8759

**Comment by andreievg** [comment]
Add to [Tracker](https://github.com/msupply-foundation/open-msupply/issues/8791), looked at all of the outstanding comments above and created entries in the tracker
