### ISSUE TITLE
Architectural misc

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/open-msupply#623]
Collating some of the thoughts and concerns raised about architecture / wider functional issues:

- [ ] Printing to the thermal printer from android
- [x] server discovery from android, in the absence of mDNS
- [x] Diagrams to show the architectural options
- [x] Run the server as a service without external utilities
- [x] Update of the service, to handle invalid config errors

**Comment by mark-prins** [comment]
giving up on the thermal for now
