### ISSUE TITLE
Report PDF printing

### ISSUE THREAD

**Issue by clemens-msupply** [openmsupply/open-msupply#68]
Goal: Allow a user to print a selected report as a PDF file. In the future report printing should also be possible as an automated task on the server (i.e. data fetching, document generation and PDF printing needs all be done on the server).

### Printing templates:
- Tera templates to specify a document to be printed
- Tera files are stored in the existing report table on the central server ("editor" column should be used to specify the report type)
- Other resources like logos, css, could possibly stored in this table as well

### Data queries:
- default queries: e.g. to get the full invoice data
- custom query: be able to specify a custom GQL query (also stored in the report table, e.g. along with the template or as a special "editor" type)
- a custom query should be evaluated with the permissions of the requesting user. Doing a self request with the Bearer token of the user is probably the easiest way to achieve this

### PDF printing:
- Use headless chrome to generate a PDF
- TODO: does it work on Android?

### API endpoint:
- `/printReport(reportId: String)`: The endpoint does the following:
  1) Looks up the requested template and query
  2) Queries the data
  3) generates a HTML doc from the template (using the queried data).
  4) The HTML file is then converted to a PDF file and returned to the caller.
- general purpose `/printHtml` to print any html to pdf (nice to have but not needed)

### Tasks:
- [x] #139
- [x] define new editor type(s) (e.g. json blob that holds all data, containing, tera file, query, images, link to other report data records, 
etc..)
- [x] service for printing a report
- [x] endpoint for printing a report
- [ ] https://github.com/openmsupply/remote-server/issues/954
- [ ] https://github.com/openmsupply/remote-server/issues/980
- [x] report builder cli (PR https://github.com/openmsupply/remote-server/pull/1028)
- [x] https://github.com/openmsupply/open-msupply/issues/71

**Comment by mark-prins** [comment]
Adding to v1 - though not all of this is required. 
Would just like the default reports tidy, and the sync of reports tested ( I think it is done? )

**Comment by clemens-msupply** [comment]
Yes reports should be synced.

**Comment by clemens-msupply** [comment]
Will close for now since main paints are done
