### ISSUE TITLE
Repack

### ISSUE THREAD

**Issue by andreievg** [openmsupply/open-msupply#694]
## Repack Pack

Originally called `split pack` but it also deals with consolidating packs, so decided to reference is as repack for now.

See comment below for context.

## Scope

Mirror functionality of: https://docs.msupply.org.nz/items:splitting_a_stock_line.

```
The Split feature of mSupply provides us with the ability to break down stock into smaller pack sizes, consolidate it into larger pack sizes or move part or all of a stock line to a new location. Here's how to use it:
````

**answers** below from meeting on 27/03, Dhanya, Craig, Mark, Andrei

### Priority 1

 - [x] End points
     * https://github.com/openmsupply/open-msupply/issues/1435
     * https://github.com/openmsupply/open-msupply/issues/1434
   
 - [x] New tab in stock info
      * https://github.com/openmsupply/open-msupply/issues/1443
      * https://github.com/openmsupply/open-msupply/issues/1445

- [x] Sync
     * https://github.com/openmsupply/open-msupply/issues/1446
   
### Priority 2

- [x] End points
     * https://github.com/openmsupply/open-msupply/issues/1448
       
 - [x] New tab in stock info
      * https://github.com/openmsupply/open-msupply/issues/1449

- [ ] Make sure that updating sites can see historic repack (would need to mark sync_buffer or transactions with `repack` type as needing to integrate during next sync 

### Priority 3
- [ ] https://github.com/openmsupply/open-msupply/issues/1432
- [ ] Ability to do remainder ?
- [ ] [Repack the whole batch ?](https://github.com/openmsupply/open-msupply/issues/694#issuecomment-1484243211)

## Questions

1. Do we want to keep basic location movement separate ? Or should it be the same functionality ? **answer**  yes, can do it both ways, have drop down for location in stock view and extra tab to split and move stock to location, the later allows printing of action for warehouse personnel. We shouldn't create repack when just doing the location movement (when stock quantity didn't change)
3. Where is the entry point for this functionality ? **answer** for not from stock modal, a new tab there with both history and new move/split operation
4. Should we have a way to view historic `repacks` (i.e. I forgot to print a repack, but need to give the print out to the warehouse staff to action) ? **answer** yes but as a secondary features

## Designs

I think the basic design should be quite simple, very similar to 

![split pack](https://docs.msupply.org.nz/_media/items:item_split.png)

For reference, p = pack, np = number of packs

But I think we should show to the user what the result should be before they press OK. I just made a mistake of entering 1 in mSupply split UI for the first field thinking it would be number of packs to split, it turns out it was a quantity field and ended up with a fraction.

5. Also we should decide about the fraction, do we allow it or do we split the remainder in another pack ? **answer** first iteration just disallow, could add remainder after, no fractions.
   * i.e. 100p x 2np split into 7 = 7p x 28np + 4p x 1np
6. Default location should be current pack location or nothing ? **answer** yes
7. Remainder location should only show up when remainder is shown ? **answer** yes

There is not `draft` state for the split. So the printing should be done after confirmation (so instead of exiting on OK, can stay on the page and if split was confirmed can print it)

First UI iteration should not worry about style and exact positioning, just make sure logic is sound and all of the info is displayed, styles can be tidied up once we see the picture of the functionality

## Other notes

To front end repack should be free from transaction/invoice logic, I was thinking we can use some existing types but realised it would be simpler to have a new type because when split/repack is in `draft` state those types would have to be manually constructed (with default for quite a few compulsory fields). 

After some further thinking about API and it's consumption, it would be much easier to allow location movement on repack only when there is actual repack (this is if we want to avoid creating invoices/transactions without movement). Since if we only do the location movement then it's hard to show historically together with repack and also to translate location movement to RepackNode, if location movement really needs to be printed we can add an icon next to stock line drop down, if location was changed.

```graphql
RepackNode {
    id: String
    repackId: Sring
    batch: String
    datetime: Timestamp
    from: RepackStockLineNode,
    to: RepackStockLineNode
}

RepackStockLineNode {
    packSize
    numberOfPacks
    stockLineNode and stockLineId (when needed, shouldn't be needed now)
}

InsertRepackInput {
    stockLineId: String
    numberOfPacks: Number
    newPackSize: Number
}
```

8. origin_stock_line_id can be added to address historic link to previous batch ? (can be deduce by looking at transactional history, but much easier to add it when pack is split) **answer** needs some further thinking and another [issue](https://github.com/openmsupply/open-msupply/issues/1432) to figure it out fully, some takeaways form the meeting:
    * `original_stock_line_id` would mean first stock line that introduced the stock in facility, whereas `origin_stock_line_id` is the previous stock line from the split/consolidation (first split those two would be the same but if stock was split more then once then they will differ and some info would be lost if we recording just original_stock_line_id
    * It really depends on what we are trying to capture, if it's just "what happened to stock that was supplied by some supplier", original_stock_line_id would do, if we need to know who changed expiry date, then we need to record `origin_stock_line_id` etc...

### Some more context: 

Full Repack: https://docs.msupply.org.nz/items:repacking
Split Pack: https://docs.msupply.org.nz/items:splitting_a_stock_line

Placeholder issue, to be fully broken down, but good place to add notes form chats:

Craig:

1. The “split” functionality in mSupply has proved by far the most useful cf the original “repack” form.
5. the current repack form is a mess due to me. We encountered in the Sols that they might grab “10 x 1000” and “20 x 500” as input, and output “1000 x 20” so we we recoded it to allow this- bad idea in retrospect. Not sure it was ever used, and for each output you really want to know whether they came from batch a (the 1000s) or batch b (the 500s), so comingling like this broke the audit trail
7. Currently I think people use split just to change a location (of the whole batch). Or you can change a location by double-clicking a stock line and just changing it (log records will be created). Neither of these are ideal. i think we should have a dedicated “location_movement” ledger- possibly already in the replenishment work

A couple of extras:

location_movement (i think it was added during mobile cold chain implementation, as we needed to remember what temperatures batches were exposed to)

![Screen Shot 2022-10-06 at 12 37 35 PM](https://user-images.githubusercontent.com/26194949/194182782-7b961d09-a651-45ca-b452-99ab8d2cb130.png)

Similar to the above, should consider what happens to temperature logs associated with a batch (don't need to implement anything special but should have a strategy for this use case)

### Job code 
OMS:REPAC

**Comment by mark-prins** [comment]
Added issues #729 and #730 for the location aspects of this issue

**Comment by andreievg** [comment]
Doing pack to one for planned deployments: https://github.com/openmsupply/open-msupply/issues/973, so repack/split can wait

**Comment by andreievg** [comment]
1. Do we want to keep basic location movement separate ? Or should it be the same functionality ?

We do have an issue for location movement to be added to stock menu: https://github.com/openmsupply/open-msupply/issues/1398, I think this could be secondary to this functionality, since in this view we can print out split/consolidate/location movement request, which I think is the process of doing this in a Warehouse

**Comment by andreievg** [comment]
2. Where is the entry point for this functionality ?

Stock menu for now should be enough, a button to split/consolidate or move pack to new location, can also view these operations from there, if we decide to do it.

**Comment by andreievg** [comment]
3. Should we have a way to view historic repacks (i.e. I forgot to print a repack, but need to give the print out to the warehouse staff to action) ?

I like this idea, see answer to `2` about it

**Comment by andreievg** [comment]
4. Also we should decide about the fraction, do we allow it or do we split the remainder in another pack ?

I think we should try and avoid fractions, and only have them when absolutely necessary, so would suggest having a remainder generated, and error if we are consolidating and there is not enough quantity specified

**Comment by andreievg** [comment]
5. Default location should be current pack location or nothing ?

Current pack locaiton

**Comment by andreievg** [comment]
6. Remainder location should only show up when remainder is shown ?

Yes and defaults to current pack location, not new location

**Comment by andreievg** [comment]
7. origin_stock_line_id can be added to address historic link to previous batch ? (can be deduce by looking at transactional history, but much easier to add it when pack is split)

Yes I would like to add it

**Comment by mark-prins** [comment]
Some thoughts and brief replies on the questions:

> 1. Do we want to keep basic location movement separate ? Or should it be the same functionality ?

Separate. If I want to change location, then get shown a modal asking me about pack size I'd get confused. I just want to change the location. Why isn't there a dropdown where I select a new location?

> 2. Where is the entry point for this functionality ?

Agree, the stock line edit modal is a handy place for it. I'd simplify and just have split though (like the mSupply version), and not try to split into multiple qty + pack sizes. You can always split some of the result into different pack sizes if you need.

> 3. Should we have a way to view historic repacks

Yes! Just add to the log though, it's an action on a stockline which is what the log shows.

> 4. Also we should decide about the fraction, do we allow it or do we split the remainder in another pack ?

Agree - fractions are evil. Prevent fractional pack size splits?

> 5. Default location should be current pack location or nothing ?

Current location

> 6. Remainder location should only show up when remainder is shown ?

Yes

> 7. origin_stock_line_id can be added to address historic link to previous batch ? (can be deduce by looking at transactional history, but much easier to add it when pack is split)

yes, nice

**Comment by mark-prins** [comment]
Oh, and additional thought - when looking at the mSupply modal my question was "can we just have a 'repack the whole lot' button?"
Less necessary if we default the quantity to the total quantity

**Comment by andreievg** [comment]
Moved remainder to carry over epic: https://github.com/openmsupply/open-msupply/issues/1923

Thank you @roxy-dao and @mark-prins for implementation, this looks great !
