### ISSUE TITLE
Testing feedback

### ISSUE THREAD

**Issue by roxy-dao** [openmsupply/open-msupply#696]
Initial testing (updated as more bugs are found 😄)

#### General
- [x] #756 Internal orders, stock and stocktake don’t have shortcuts? 
- [x] #708 Clicking on `Outbound Shipment` on Dashboard pops up with `Customer` list, but clicking on `Order More` redirects to `Internal Order` page... should be consistent?
- [x] #708 `New Inbound Shipment` button disabled on Dashboard?~~
- [ ] Token expires after a few minutes sometimes (less than 10 minutes) and requires logging in again... but sometimes lasts for hours...? ( raised as #1019 )
- [x] #910

#### Invoices 
- [x] #756 `Customers` for invoices should not include `Patients` (Programs)
- [x] #726 Tax input in service line modal doesn't allow for decimal inputs, but tax input in side bar for service does
- [x] #741 Tax for outbound shipments is incorrect (might be confusing for users since tax is set on invoice line but displayed for overall invoice)
- Add an item -> set tax (example tax is set at 10%)
- Add second item -> tax is recalculated as x% of first item, but second item won't have tax
<img src="https://user-images.githubusercontent.com/61820074/194446971-dca04b5f-aa7c-4876-8e7e-134e92fa4efe.png" width="250"/>
<img src="https://user-images.githubusercontent.com/61820074/194447083-adc406dd-68ad-46ec-9f4b-f064b92c3167.png" width="250"/>
^ (sell price, total before tax, total after tax, and tax fields)

- [ ] Total on service charges doesn't update immediately after putting amount and tax in on modal (raised as #1020)
- [x] #726 When outbound shipments are created from requisitions, message should be `...created on xx-xx-xx by omsupply_system` since request requisitions are always created by the system??
![Image](https://user-images.githubusercontent.com/61820074/194776660-2b5709c9-22fa-495c-8595-4f485f03c5f5.png)
- [x] #741 Tax cannot be added to inbound shipments service charge (but in the docs it says that you can)
- [x] ~~Transport details don't appear on manually created inbound shipments (Should add or clarify this in docs)~~ (Note: Manual inbound shipments don't need transport info)
- [ ] If item doesn't have a sell price then this can't be adjusted in invoice (raised as #1020)
- [x] https://github.com/openmsupply/open-msupply/issues/188 (Invoice goes to store before name change, any updates to the invoice will also go to the name before changed)
- [x] #756 `Log` is underlined when you first go into an invoice instead of `Details`
![Screen Shot 2022-10-10 at 12 47 39 PM](https://user-images.githubusercontent.com/61820074/194785039-ed72560e-8d82-493f-89e6-b68d589e27be.png)
- [x] #741 Total on transferred `Inbound Shipment` is incorrect and does not include the tax in the total (fields are generated in inbound shipment line as - `total_after_tax: cost_price_per_pack * number_of_packs as f64` and `tax: Some(0)` 🤔 ) What happens to the tax?!
- [x] Sell and cost price can only be numerical (??)
- [x] For manual `Inbound Shipments`, totals aren't being calculated when inputting `cost`
- [x] #726 Outbound shipment lines don't show batch of item
- [x] #756 `Select all` in the stocktake modal prunes all stock with 0 packs, should this do the same in `Outbound Shipments`? 

#### Requisition
- [x] #712 No logging done for `Outbound Shipments` that get generated from `Requisitions`
- [x] #712 `Requisitions` -> `Issued` and `Remaining` labels unclear
- [ ] Target Quantity should be spaced out more to fit all the numbers (Internal Orders)
![Image](https://user-images.githubusercontent.com/61820074/194777481-d89c4141-40e7-4e72-91cb-f6ab40bcb491.png) (added to #873)
- [ ] Open requisition -> don't supply requested stock -> click create shipment -> `Error: All of the lines of this requisition already have a matching shipment line` (raised as #1021)
- [x] #712 Internal orders aren't being pruned if added from master list and aren't being requested

#### Stocktake 
- [x] #720 Changing expiry date in stock take does not save the expiry date on stock line
- [ ] Can't update location/batch/sell or cost price of item (if does not exist) (added to #938)

#### Location
- [x] #710 Added location but location doesn't show up in invoice or stock take
<img src="https://user-images.githubusercontent.com/61820074/194781450-5f615072-47de-4a53-86f7-eed0179cb53f.png" width="500"/>
<img src="https://user-images.githubusercontent.com/61820074/194781486-0f0d52c6-b19a-4f6a-9cee-f1b890d44c07.png" width="500"/> 

#### Item
- [x] #710 New items that have never been used in the store before will have 0 months of stock... might be confusing?

#### Master Lists
- [x] ~Pagination disappears if Master List is too long (Update: Doesn't exist, should add instead of having a long list to scroll through?)~
![Screen Shot 2022-10-11 at 9 24 24 AM](https://user-images.githubusercontent.com/61820074/194946717-1c9b2dda-2a20-4b04-afc1-917a2590a3e1.png)

#### Sync
- [ ] Processors stops working after a while (can't see any processing in console either and can't quit server, had to close the terminal and delete the database to get it working again)
- [ ] All fields disabled when initialisation error is unknown (not even sure how this error happened in the first place...nothing was displayed in console... might have been a corrupt data file... and sync api is called every second after 👀 ... had to delete browser history to get initialisation working again), refreshing doesn't re-enable the fields either
  <img src="https://user-images.githubusercontent.com/61820074/194442732-ad15bf6f-96d4-4848-95d4-a335b2a59068.png" width="250"/>
(these have been added to #963)

#### Docs
~~- **Customers:** `There may be more customers in our organisation.` ...your organisation.~~
~~- **Items:** `How much stock currently available in your store for this store` either in your store or for this store...?~~
~~- **Internal** Orders: `Select a Supplier by pressing on its name. ` ...on their name.~~
~~- **Inbound** shipments: `Cancel Button` -> close button...?~~

**Comment by mark-prins** [comment]
🙏  @roxy-dao

**Comment by mark-prins** [comment]
Docs have been updated - and published 😁

**Comment by mark-prins** [comment]
I've taken issues, master lists and locations and copied the items into #710

**Comment by mark-prins** [comment]
> Logo change doesn't work (??)

Unable to replicate this. The logo needs to be an svg and there are examples in [google drive](https://drive.google.com/drive/u/2/folders/1rnMPi5OZiO35pI1FKnGsbpxAG7iuQw6f) if you want

> Reports for printing don't have templates so are unavailable (Invoice, Requisition, Stocktake)

There needs to be reports in mSupply configured - and these will sync to omSupply. Sample json files in [google drive](https://drive.google.com/drive/u/2/folders/1qKCmVDujC7LF4EoO8ZCd7SI5GSRSJPwM)

**Comment by DhanyaHerath** [comment]
Hey @roxy-dao did that timestamp one get fixed? I feel like I remember it being mentioned in standup but can't find the issue?

**Comment by roxy-dao** [comment]
> Hey @roxy-dao did that timestamp one get fixed? I feel like I remember it being mentioned in standup but can't find the issue?

Hasn't been fixed and no issue for it at the moment. I think HSH was having some DateTime issue too~...

**Comment by DhanyaHerath** [comment]
@roxy-dao I just added an issue anyway :)

**Comment by mark-prins** [comment]
Issues raised or linked for the remaining items.
