### ISSUE TITLE
Cold chain API

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/open-msupply#702]
Would be good to implement the REST API, as per mSupply, that allows the cold chain app to sync data with desktop.

We'd need to implement the various `coldchain_*` methods in mSupply to provide the basic endpoints
- authentication ( validate user credentials / JWT )
- helper methods
  - JWT validation
  - body validation
- sensor ( PUT request to store sensors )
- temperature breach ( PUT request to store temperature breaches )
- temperature log ( PUT request to store temperature log entries )

## Tasks
- [ ] Create tables
- [ ] Implement sync for the tables (?)
- [ ] Add REST API support
- [ ] JWT token support
- [ ] Store credentials / permission type to validate against
- [ ] Validate login and JWT
- [ ] Implement REST methods
- [ ] Add graphQL queries
- [ ] Add support in UI

TODO: how is the `sensorLog_createBreaches` method called?

## Documentation

- https://github.com/openmsupply/msupply-cold-chain/issues/19
- [Testing template](https://github.com/openmsupply/msupply-cold-chain/issues/142)
- [Configuration](https://docs.google.com/document/d/1AeLKsfVB1ZwYPa81VylFtE97_KWNR0QJoNZdypKj4aw/edit#heading=h.5oqryynsuffb)
- Some screenshots and helpful information in [this issue](https://github.com/sussol/msupply/issues/9979) too

## Tables
In mSupply the following were created. Likely the same will be needed in oms

- [sensor]
- [sensorLog] an aggregation of [temperature_log] data. rename to [sensor_log]
- [sensorLogItemLineJoin] connects a sensor to an item line. rename to [sensor_log_stock_line_join]
- [temperature_log] a full log of temperatures from each sensor
- [temperature_breach]
- [temperature_breach_config]

[![](https://mermaid.ink/img/pako:eNqVVk2P2yAQ_SvIp620ufWwiqqe-g96jYQmMHHo8mEBTjfazX8vOG6CMbBZHyIy73mYN1_ye8cMx27bMQnO_RLQW1A7TcLjUDtjyY-PzWY-U2n6FIv_yWbz8ZNIw8ALo8uo88biCsoc08Bir1QKjfSPEStXOX5zPRuvfI9qQAt-tJjcPzlpEJbhl33cNRTx1Li3COy4Jl_t7ZhSTj2shadyZCllbafM6IPoa6_N8COhLqmtWBbMUseQLRGcPHl8898ye2hO9DSgESxT9uA92jOVeEJJng7SgH_JScJRYF6ckDztjZE5HIbAxzA1shgc5eDRCxXY8dd5UMPqlVkIrYUee5ejhPNj3noqdNBxgqAhnL7nDAWMAucWnSvfp2G6oYAM1sTxVsgfCWWqZVVVUt4s19MmSQb3_WomeW1vw72y11JKCPS9xX4CMyQKWoshseBC_x-GtOakLJA0lF3KAvPNdBNckEySjUVL6N1rhi4uz1ZQPcX1OrfSXO3Ces2-nMzihnhU85Velw3sVZu_EnmPPKs66lb3t7JSlw7WN31-npzliixQj2Hgj0aG2Ec79_-iLndC6lXBm1CjWqe-zBa6zD4P-JW6zCrac8CMNKNdmTk6ZsVQmPCAlaWTylZvVzPBor4SYc4ebTVxYF2z9gmr0gKl5JLk6Z47hVaB4OEbbUrorvNHVLjrtuHI8QCj9Ltupy-BCqM3v8-adVtvR3zuxiF25fxV120PIB1e_gFf9FAV?type=png)](https://mermaid.live/edit#pako:eNqVVk2P2yAQ_SvIp620ufWwiqqe-g96jYQmMHHo8mEBTjfazX8vOG6CMbBZHyIy73mYN1_ye8cMx27bMQnO_RLQW1A7TcLjUDtjyY-PzWY-U2n6FIv_yWbz8ZNIw8ALo8uo88biCsoc08Bir1QKjfSPEStXOX5zPRuvfI9qQAt-tJjcPzlpEJbhl33cNRTx1Li3COy4Jl_t7ZhSTj2shadyZCllbafM6IPoa6_N8COhLqmtWBbMUseQLRGcPHl8898ye2hO9DSgESxT9uA92jOVeEJJng7SgH_JScJRYF6ckDztjZE5HIbAxzA1shgc5eDRCxXY8dd5UMPqlVkIrYUee5ejhPNj3noqdNBxgqAhnL7nDAWMAucWnSvfp2G6oYAM1sTxVsgfCWWqZVVVUt4s19MmSQb3_WomeW1vw72y11JKCPS9xX4CMyQKWoshseBC_x-GtOakLJA0lF3KAvPNdBNckEySjUVL6N1rhi4uz1ZQPcX1OrfSXO3Ces2-nMzihnhU85Velw3sVZu_EnmPPKs66lb3t7JSlw7WN31-npzliixQj2Hgj0aG2Ec79_-iLndC6lXBm1CjWqe-zBa6zD4P-JW6zCrac8CMNKNdmTk6ZsVQmPCAlaWTylZvVzPBor4SYc4ebTVxYF2z9gmr0gKl5JLk6Z47hVaB4OEbbUrorvNHVLjrtuHI8QCj9Ltupy-BCqM3v8-adVtvR3zuxiF25fxV120PIB1e_gFf9FAV)

### Authentication
Login
- The server accepts an object with the shape `{username: string, password: string}`
- The credentials are validated against the store credentials, which we don't have. Suggest that we add a permission type for users of `COLD_CHAIN_API` and manually (for now) create a user and grant this permission. Next step is to take the store credentials during sync and create a user
- If validated, the server creates a JWT token and returns the cookie. This contains the storeID currently - we will be consuming the JWT so can define the shape

Validation
- If a JWT is presented, this is checked for a valid storeID

### Sensor
- Method must be `PUT` ( or return 405 )
- body of the request is validated (see `coldchain_bodyV1Validation`) or return 400
- Create a record for each valid sensor supplied
- return JSON of `{ valid: Sensor[], invalid Sensor[] }`

### Temperature Breach
- body of the request is validated (see `coldchain_bodyV1Validation`)
- body of the request is validated (see `coldchain_bodyV1Validation`) or return 400
- Create a record for each valid temperature breach supplied
- return JSON of `{ valid: Sensor[], invalid Sensor[] }`

### Temperature Log
- body of the request is validated (see `coldchain_bodyV1Validation`)
- body of the request is validated (see `coldchain_bodyV1Validation`) or return 400
- Create a record for each valid temperature_log supplied
- return JSON of `{ valid: Sensor[], invalid Sensor[] }`

### mSupply 
- An alert modal sourced from the `/Resources/breach` app is used to show breaches
- The modal is shown based on a trigger on the `[temperature_breach]` table
- A list of the following items is available from the `Item` > `Vaccines` menu item
  - Temperature breach configurations
  - VVM status
  - Sensors
  - Temperature logs

For reference - this is the mSupply alert window:

<img width="415" alt="Screen Shot 2022-10-19 at 3 47 14 PM" src="https://user-images.githubusercontent.com/9192912/197626248-22ce6930-783e-46f6-9cba-5a26f6f71f18.png">

### Proposed
- A dashboard widget to display breaches
- Polling / websocket to show breach events. The client can store an identifier of the last shown breach and notify if anything new is available on the server
- Attach an alert notification to stock lines somehow
- Add a `Vaccines` menu item which would have the following sub-menu items, each of which is a read-only list view:
  - Temperature breach configurations
  - VVM status
  - Sensors
  - Temperature logs
- GraphQL queries for each of the four items above

For the vaccines menu item, I'd suggest under `Inventory`. We don't currently have 3rd level nav, so I would add a `Vaccines` item, and have tabs for each of the four lists.

**Comment by roxy-dao** [comment]
Closing as dup of #1955
Will update issue with relevant infomation
