### ISSUE TITLE
location_movement table

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/open-msupply#730]
In mobile, we've added a `[location_movement]` to track when stock enters and leaves a location. This is so that we can match items to locations temporally i.e. we can cross reference any breaches in temperature more accurately to when items were in a particular location.

## Questions
- Is this overkill?
- Should we only track vaccines in this way?
- How do we prune the table? it could result in a lot of records over time

## Tasks
- [x] Create table (see below)
- [x] Via stocktake or invoice - when stock is added, a movement is created with an `entry` datetime
- [x] Via stocktake or invoice - if the stock level is reduced to zero, an `exit` datetime is recorded
- [x] When editing a stock line: if the location has changed, an `exit` datetime is recorded, and a new movement is created

**location_movement**

[![](https://mermaid.ink/img/pako:eNqFUUkOwjAM_ErkE0jwgR448QOukSorMRCRBSUuApX-HVNadoEPUeQZz2TiFkyyBBUYj6UsHW4yBh2VlE8G2aVYh3SgQJHVfH5eqMIp00_G2P4nY3a1d3HQ6v0_ye0NVcpZNWE68nRs3KnOvgIyRbm2yMQukEzJWRjD_sE4Ov5JeDyu_vDt87-3u-cQPUO135FB9xs6JhLsjo6ut4IZBMoBnZWN9RIaeCsfpaGSq6U1Np416NgJFRtOq1M0UHFuaAbN_pp52DFUa_SFugsJxaov?type=png)](https://mermaid.live/edit#pako:eNqFUUkOwjAM_ErkE0jwgR448QOukSorMRCRBSUuApX-HVNadoEPUeQZz2TiFkyyBBUYj6UsHW4yBh2VlE8G2aVYh3SgQJHVfH5eqMIp00_G2P4nY3a1d3HQ6v0_ye0NVcpZNWE68nRs3KnOvgIyRbm2yMQukEzJWRjD_sE4Ov5JeDyu_vDt87-3u-cQPUO135FB9xs6JhLsjo6ut4IZBMoBnZWN9RIaeCsfpaGSq6U1Np416NgJFRtOq1M0UHFuaAbN_pp52DFUa_SFugsJxaov)
