### ISSUE TITLE
JSON Document integration

### ISSUE THREAD

**Issue by CarlosNZ** [openmsupply/open-msupply#81]
Just a quick summary of what we discussed in meeting regarding steps forward to get this working. Very broad strokes, will add more detail in specific issues.

### Back-end

- [x] Setup GraphQL node for "Document" which returns a JSON document (from DocID) along with associated JSON schema and UI Schema
- [x] Mutation creates new document and updates the appropriate database table (e.g. name/patient), and returns the new Document
- [x] Name endpoint should also have a "document_id/name" field containing the id of the most recent doc (which its based off)

### Front-end

Implement for "Patient" DetailView:

- [x] Configure [JSONForms](https://github.com/eclipsesource/jsonforms) PR #148 
- [x] Create renderers for:
  - [x] Text input
  - [x] Select (drop-down)
  - [x] Label (for text info)
  - [x] Date Picker
  - [x] Array (multiple items in element, eg. addresses) #149  PR #173 
- [x] Patient Detail View queries to Document endpoint #150 
- [x] Patient Detail View Mutation on Save #151
- [x] Make "Patient" detail view a page rather than a modal #152
- [x] (moved out of this epic since its blocked by other work first) Handle editability (via permissions?), and inject into uiSchema #153 
- [x] Create new document/patient #154
- [x] Schema validation #174

**Comment by CarlosNZ** [comment]
### Suggested front-end implementation:

Since we will only be using JSONForms with Document/schema querying, we'll only need one Database query/api configured, regardless of the specific implementation.

Suggestion is to create a `useDocumentForm` hook to abstract away the database and form functionality together in one place. 

We invoke with `const {JsonForm, saveData, loading, error} = useDocumentForm(<docId>)`

Then in the hook we have:
- library of renderer/tester components (with default materialRenderers as fallbacks until we build up our own library)
- api queries and mutations for database retrieval (structured with similar pattern to existing ReactQuery hooks)
- parser for query -- separates returned data into `data`, `schema`, `uiSchema`, which are used accordingly:
  - `data` becomes a `useState` value which is updated on form change, keeps the same shape as the original document
  - `schema` and `uiSchema` consumed by `JsonForms` component
- `JsonForms` component takes above plus renderer/tester library as props.

Then the calling component just displays the returned `JsonForm` component as is, and runs the `saveData` function (database mutation) when Submit/Save button is pressed (Submit button exists outside `JsonForm`)
 
Question regarding editing forms vs displaying only: Where is it determined who can edit Documents? Is it permission-based, and will it be different depending on the user? How will the front-end get this information -- can it be returned as part of the getDocument query?

And will we have a situation where editing permissions can change on a per-element basis? If so, the back-end might have to generate a dynamic ui-schema on the fly with the "editability" status of each element injected into the ui-schema that is returned so the front-end knows which elements to make editable.

Thoughts @mark-prins @clemens-msupply ?

**Comment by clemens-msupply** [comment]
> Question regarding editing forms vs displaying only: Where is it determined who can edit Documents? Is it permission-based, and will it be different depending on the user? How will the front-end get this information -- can it be returned as part of the getDocument query?

It is permission based but currently there is no endpoint to get the user's permissions or which endpoint need which permissions (https://github.com/openmsupply/open-msupply/issues/67)... So just assume you have permissions for now.

> And will we have a situation where editing permissions can change on a per-element basis? If so, the back-end might have to generate a dynamic ui-schema on the fly with the "editability" status of each element injected into the ui-schema that is returned so the front-end knows which elements to make editable.

No its not planned, you can query/mutate the whole document. Think otherwise it would get confusing.
